import { EmploymentTypes } from "../enums/employment-types";
import { ScheduleTypes } from "../enums/schedule-types";
import { SeniorityLevels } from "../enums/seniority-levels";
import { Skills } from "../enums/skills";
import { EmploymentHistoryItem } from "../types/employment-history-item";

export const EMPLOYMENT_HISTORY: Array<EmploymentHistoryItem> = [
  {
    company: "Kibeam Learning",
    companyUrl: "https://kibeam.com/",
    dateStart: new Date(2025, 2),
    dateEnd: new Date(2025, 12),
    description: [
      "Executed, coordinated, and monitored simultaneous deployments of 3 or more projects to facilitate the release of features which included changes to all parts of the stack",
      "Spearheaded upgrade of front-end applications to Svelte 5 from Svelte 4, systematically transitioning features while improving application stability and without introducing regressions",
      "Redesigned and audited complex pre-existing projects to drastically improve stability and user experience",
      "Triaged and remedied bugs in multiple projects and programming languages, including performance and concurrency concerns",
      "Added unit tests to the organization's previously-untested front-end projects and created documentation and repeatable architecture to facilitate growth of automation",
      "Developed launch automation tasks and created thorough technical documentation of complex existing systems with little-to-no onboarding",
      "Added comprehensive onboarding and technical documentation to the company's knowledge base to facilitate knowledge transfer and drastically improve the ramp-up time for employees who were new to the relevant projects (in one case, three weeks was reduced to under 1 hour)",
      "Interfaced directly with internal stakeholders in both a support and advocacy capacity; collected concerns, usability issues, and bug reports to create actionable plans for improving the tooling",
      "Mentored technical designers on core programming principles and project architecture and participated in paired programming exercises to help them transition into junior developer roles"
    ],
    jobTitle: "Senior Full-Stack Consultant",
    location: "Ottawa, ON",
    schedule: ScheduleTypes.Remote,
    seniority: SeniorityLevels.Senior,
    skills: [
      Skills.FullStack,
      Skills.JavaScript,
      Skills.TypeScript,
      Skills.Svelte,
      Skills.SvelteKit,
      Skills.UX,
      Skills.CSS,
      Skills.SCSS,
      Skills.HTML,
      Skills.API,
      Skills.CSharp,
      Skills.DesignWeb,
      Skills.Figma,
      Skills.Docker,
      Skills.Python,
      Skills.Testing,
      Skills.Vitest,
      Skills.Jest,
      Skills.Regex,
      Skills.Cybersecurity,
      Skills.PostgreSQL,
      Skills.MySQL,
      Skills.ML,
      Skills.AWS,
      Skills.Mentorship,
      Skills.Documentation,
      Skills.TechnicalWriting
    ],
    type: EmploymentTypes.ContractFull
  },
  {
    company: "Kinaxis",
    companyUrl: "https://www.kinaxis.com/en",
    dateStart: new Date(2024, 8),
    dateEnd: new Date(2024, 10),
    description: [
      "Developed additional functionality for reusable components in the Kinaxis design system",
      "Investigated and thwarted bugs across multiple layers of the tech stack",
      "Improved developer onboarding efficiency by documenting and correcting issues in the provided resources",
      "Developed a lightweight and extensible JavaScript framework for building dynamic, API-driven web pages with JSON over the course of 4 days during the 2024 Kinaxis Hackathon"
    ],
    jobTitle: "Senior Software Developer, Clients, Front-End Technologies",
    location: "Kanata, ON",
    schedule: ScheduleTypes.Hybrid3,
    seniority: SeniorityLevels.Senior,
    skills: [
      Skills.FrontEnd,
      Skills.JavaScript,
      Skills.TypeScript,
      Skills.React,
      Skills.CSS,
      Skills.SCSS,
      Skills.UX,
      Skills.Testing,
      Skills.Jest,
      Skills.Jasmine,
      Skills.TestCafe,
      Skills.SQL,
      Skills.TestCafe,
      Skills.Figma,
      Skills.Proprietary
    ],
    type: EmploymentTypes.ContractFull
  },
  {
    company: "Cinchy, Inc.",
    companyUrl: "https://cinchy.com/",
    dateStart: new Date(2022, 10),
    dateEnd: new Date(2024, 8),
    description: [
      "Spearheaded a major refactor of our metadata-driven forms application, removing complexity from the workflow and eliminating previously untraceable errors; all following issues could be diagnosed within hours instead of days",
      "Crafted complex features within multiple applications of a large existing codebase with a strong emphasis on usability and extensibility, ensuring that code quality universally improved with each iteration",
      "Oversaw simultaneous Angular upgrades from versions 12 to 17 for 3 projects with shared dependencies",
      "Added inline comments, function descriptions, and process documentation to large existing applications, including a guide on how to write meaningful unit tests without introducing memory leaks and a multi-app Angular compatibility matrix",
      "Added strong typing to deep asynchronous processes and enforced immutability for custom form data in our Forms and Connections apps to ensure that data passing between components remained accessible and consistent",
      "Worked closely with the platform team to troubleshoot and develop APIs and queries, and helped coordinate work on data-centric features across the whole stack"
    ],
    jobTitle: "Experiences Developer III",
    location: "Ottawa, ON",
    schedule: ScheduleTypes.Remote,
    seniority: SeniorityLevels.Senior,
    skills: [
      Skills.FullStack,
      Skills.JavaScript,
      Skills.TypeScript,
      Skills.Angular,
      Skills.React,
      Skills.CSS,
      Skills.SCSS,
      Skills.HTML,
      Skills.UX,
      Skills.MaterialUI,
      Skills.Regex,
      Skills.ESLint,
      Skills.API,
      Skills.SQL,
      Skills.CSharp,
      Skills.Docker,
      Skills.DesignWeb,
      Skills.Figma,
      Skills.Proprietary
    ],
    type: EmploymentTypes.FullTime
  },
  {
    company: "Shopliftr",
    companyUrl: "https://www.shopliftr.com/",
    dateStart: new Date(2021, 0),
    dateEnd: new Date(2022, 10),
    description: [
      "Spearheaded a major refactor of both API and model layers across our full stack to improve application stability, ensure data integrity with validation decorators, and reduce maintenance overhead for new code",
      "Built new features and fixed critical bugs for the company's key tooling",
      "Wrote, maintained, and enforced UI/UX standards for our applications",
      "Served as the lead designer, creating designs for new features in Figma and creative for ad units in Photoshop",
      "Improved unit test coverage for shared component library and data entry platform from almost nothing to over 90%"
    ],
    jobTitle: "Senior Developer",
    location: "Ottawa, ON",
    schedule: ScheduleTypes.Onsite,
    seniority: SeniorityLevels.Senior,
    skills: [
      Skills.FullStack,
      Skills.JavaScript,
      Skills.TypeScript,
      Skills.Angular,
      Skills.UX,
      Skills.CSS,
      Skills.SCSS,
      Skills.Regex,
      Skills.API,
      Skills.NodeJS,
      Skills.DesignWeb,
      Skills.DesignGraphic,
      Skills.Figma,
      Skills.Photoshop,
      Skills.Testing,
      Skills.Jasmine,
      Skills.Jest,
      Skills.Elasticsearch,
      Skills.ESLint,
      Skills.MaterialUI,
      Skills.AWS
    ],
    type: EmploymentTypes.FullTime
  },
  {
    company: "Shopliftr",
    companyUrl: "https://www.shopliftr.com/",
    dateStart: new Date(2017, 8),
    dateEnd: new Date(2021, 0),
    description: [
      "Triaged and maintained the company's key tooling",
      "Ran quality control for numerous digital ad campaigns, including cross-referencing tracking pixels and ensuring data integrity",
      "Improved unit test coverage for shared component library and data entry platform from almost nothing to over 90%"
    ],
    jobTitle: "Front-End Developer",
    location: "Ottawa, ON",
    schedule: ScheduleTypes.Onsite,
    seniority: SeniorityLevels.Intermediate,
    skills: [
      Skills.FrontEnd,
      Skills.JavaScript,
      Skills.TypeScript,
      Skills.Angular,
      Skills.UX,
      Skills.CSS,
      Skills.SCSS,
      Skills.Testing,
      Skills.Jasmine,
      Skills.Jest,
      Skills.Photoshop,
      Skills.MaterialUI,
      Skills.Elasticsearch,
      Skills.AWS
    ],
    type: EmploymentTypes.FullTime
  },
  {
    company: "Local Line",
    companyUrl: "https://www.localline.co/",
    dateStart: new Date(2015, 8),
    dateEnd: new Date(2017, 8),
    description: [
      "First developer and sole front-end resource for the duration of the role",
      "Built from scratch a web-based toolset for local farmers and food suppliers to better understand their customers and run their business, providing analytics and a digital storefront with customer-aware pricing",
      "Collaborated with the staff designer to optimise workflows before providing pixel-perfect implementations",
      "Developed a custom solution for seamlessly stacking modal dialogs in AngularJs, closing a functionality gap in the framework with a solution that prompted the SRED evaluator to recommend distribution through an open source project",
      "Educated the design team on the fundamentals of web development to help improve turnaround and drive new features"
    ],
    jobTitle: "Front-End Developer",
    location: "Ottawa, ON",
    schedule: ScheduleTypes.Onsite,
    seniority: SeniorityLevels.Intermediate,
    skills: [
      Skills.FrontEnd,
      Skills.JavaScript,
      Skills.TypeScript,
      Skills.AngularJS,
      Skills.UX,
      Skills.CSS,
      Skills.SCSS,
      Skills.SQL,
      Skills.MaterialUI
    ],
    type: EmploymentTypes.FullTime
  }
];
